apiVersion: apps/v1
kind: Deployment
metadata:
  name: exotic-pets-api
  labels:
    app: exotic-pets-api
    version: v1
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: exotic-pets-api
  template:
    metadata:
      labels:
        app: exotic-pets-api
        version: v1
    spec:
      containers:
      - name: exotic-pets-api
        image: exotic-pets-api:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: exotic-pets-secrets
              key: mongodb-uri
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: exotic-pets-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: exotic-pets-secrets
              key: jwt-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: exotic-pets-secrets
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: exotic-pets-secrets
              key: aws-secret-key
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: exotic-pets-config
              key: allowed-origins
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: exotic-pets-api-service
  labels:
    app: exotic-pets-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: exotic-pets-api

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: exotic-pets-api-route
  labels:
    app: exotic-pets-api
spec:
  host: exotic-pets-api.apps.your-cluster.com
  to:
    kind: Service
    name: exotic-pets-api-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exotic-pets-config
data:
  allowed-origins: "https://exotic-pets-frontend.apps.your-cluster.com,https://admin.exotic-pets.com"
  api-base-url: "https://exotic-pets-api.apps.your-cluster.com"
  log-level: "info"
  rate-limit-window: "15"
  rate-limit-max-requests: "100"

---
apiVersion: v1
kind: Secret
metadata:
  name: exotic-pets-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://username:password@cluster.mongodb.net/exotic-pets"
  redis-url: "redis://redis-service:6379"
  jwt-secret: "your-super-secret-jwt-key-here"
  aws-access-key: "your-aws-access-key"
  aws-secret-key: "your-aws-secret-key"
  smtp-password: "your-smtp-password"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exotic-pets-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exotic-pets-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: exotic-pets-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: exotic-pets-api